"""empty message

Revision ID: 7f8641267bb6
Revises: 
Create Date: 2020-10-17 19:50:52.356128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f8641267bb6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sqlite_sequence')
    op.create_index(op.f('ix_items_author'), 'items', ['author'], unique=True)
    op.create_index(op.f('ix_items_body'), 'items', ['body'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_items_body'), table_name='items')
    op.drop_index(op.f('ix_items_author'), table_name='items')
    op.create_table('sqlite_sequence',
    sa.Column('name', sa.NullType(), nullable=True),
    sa.Column('seq', sa.NullType(), nullable=True)
    )
    # ### end Alembic commands ###
